version: 2
jobs:
  #  build and test jobs go here
  deploy-job:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy
          command: bundle exec cap production deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master